PRODUCTS_URL = "https://www.saucedemo.com/inventory.html"
ADD_SLB_TO_CART_BTN = "id:add-to-cart-sauce-labs-backpack"
ADD_SLBL_TO_CART_BTN = "id:add-to-cart-sauce-labs-bike-light"
ITEMS_IN_CART_NUM = "xpath://div[@id='shopping_cart_container']/a/span"
ITEMS_ON_PAGE_NUM = "xpath://div[@class='inventory_list']/div"
ITEMS_ADDED_NUM = "xpath://div[@class='inventory_list']/div/div[@class='inventory_item_description']/div[@class='pricebar']/button[text()='Remove']"
ITEM_SORT = "class:product_sort_container"
CART_LINK = "class:shopping_cart_link"
